.\" Copyright (C) 2022-24 Kevin Boone 
.\" Permission is granted to any individual or institution to use, copy, or
.\" redistribute this software so long as all of the original files are
.\" included, and that this copyright notice is retained.
.\"
.TH newsman 1 "June 2024"
.SH NAME
newsman \- Read BBC news headlines using the manual viewer 
.SH SYNOPSIS
.B newsman 
.RB [--help] [--version] [topic]
.PP

.SH DESCRIPTION
\fInewsman\fR retrieves news headline feeds from the BBC, and displays them
using the manual viewer. 

.SH TOPICS 
Valid topics include: 'world', 'uk', 'health', 'business', 'politics', 
\'education', 'science', 'technology', 'entertainment'. There are others,
but only the BBC knows the complete list. 

.\" end of file
