#!/bin/bash

#===========================================================================
#
# Download BBC News headlines and format so they can be read in the
# console using the manual viewer.
#
# Requires: curl, sed, xsltproc
#
# usage: newsman [topic]
# See code below for list of topics
#
# https://kevinboone.me/clh_newsman.html
#
# Copyright (c)2024 Kevin Boone, GPL v3.0
#
#===========================================================================

VERSION=0.2a

# The base URL for BBC news feeds. %%TOPIC%% will be substituted later 
FEED_BASE="https://feeds.bbci.co.uk/news/%%TOPIC%%/rss.xml"

if [ ! -z "$1" ] ; then
  TOPIC=$1
  TITLE="Headlines - $TOPIC"
else
  TOPIC=
  TITLE="Headlines"
fi

if [[ "$TOPIC" == "-h" || "$TOPIC" == "--help" ]]; then
  echo Usage: "[-h|--help]" "[-v|--version]" newsman [topic]
  echo Topics are : world, uk, health, business, politics, education, 
  echo science, technology, entertainment. Omit topic for
  echo general headlines. 
  exit
fi

if [[ "$TOPIC" == "-v" || "$TOPIC" == "--version" ]]; then
  echo newsman version $VERSION 
  exit
fi

FEED=`echo $FEED_BASE | sed s/%%TOPIC%%/${TOPIC}/`

# The file where we will write out the XSLT stylesheet, for later use by
#  xsltprc
XSLTFILE="/tmp/newsman$$"

RESPONSE=`curl -s $FEED` 
RET=$?

if [ $RET -ne 0 ]; then
  echo $0: Can\'t download feed $FEED
  exit
fi 

if [[ ! $RESPONSE == *"BBC News"* ]]; then
  echo $0: response was not a BBC news RSS document  
  exit
fi 

if [[ $RESPONSE == *"404 - Not"* ]]; then
  echo $0: topic not found 
  exit
fi 

# Write the (simple) stylesheet to a convenient file -- we will edit
#  it in place later

cat << EOF > $XSLTFILE 
<xsl:stylesheet version="1.0"
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="/rss/channel">
.TH "BBC News" "7" "" "" "@@@TITLE@@@"
  <xsl:for-each select="item">

\fB<xsl:value-of select="title"/>\fR
.br
<xsl:value-of select="description"/>

</xsl:for-each>

</xsl:template>
</xsl:stylesheet>
EOF

# Set the title in the style sheet, so it will be written in the header
#  by the manual viewer
sed --in-place s/@@@TITLE@@@/"$TITLE"/ $XSLTFILE

# Apply the stylesheet to the RSS resonse, and pass the result
#  to the manual viewer
echo "$RESPONSE" | xsltproc $XSLTFILE - | grep -v xml \
  |  man -l -r "newsman - ${TITLE}" - 

# Remove the program-generated stylesheet
rm -f $XSLTFILE

